version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "07:30"
  ignore:
  - dependency-name: laravel/framework
    versions:
    - 8.28.0
    - 8.28.1
    - 8.29.0
    - 8.30.0
    - 8.30.1
    - 8.31.0
    - 8.32.0
    - 8.32.1
    - 8.33.0
    - 8.33.1
    - 8.34.0
    - 8.35.0
    - 8.35.1
    - 8.36.1
    - 8.36.2
    - 8.38.0
  - dependency-name: phpunit/phpunit
    versions:
    - 9.5.3
  - dependency-name: composer/composer
    versions:
    - 2.0.10
    - 2.0.11
